In [2]:
# %matplotlib inline
from utils.opconNosepokeFunctions import *


toneStartMarker = 23
trialStartMarker = 81
trialHitMarker = 51
trialMissMarker = 86
trialUnrewMarker = 87
sessionStartMarker = 61
rewardProbMarker = 83
trialProbMarker = 88
lickMarker = 22
list_sessionMarker = [12, 13]

# load files

In [16]:
animal = 'Giratina'
box = 1
date = '2025-03-05'
end_date = '2025-03-17'
path = f"L:/4portProb/Box{box}/{animal}/"       # for any les animal
# path = f"L:/4portProb_ephys/Box1_ephys/{animal}/Behavior/"      # for ephys only

files = exclude_files(get_files(path))
set_cwd(path)
files = [file for file in files if (file >=f'{animal}-{date}*.dat')& (file <= f'{animal}-{end_date}*.dat')]

# files = [r"C:\Users\dlab\Documents\OpCon v2.2 Nosepoke\Bhindi-2025-02-27-15-38-26.dat"]
# set_cwd(r'C:\Users\dlab\Documents\OpCon v2.2 Nosepoke')
files.sort()
print(files)
list_sessionMarker = [13]

df = merge_files_to_df(files)

sessdf = trializer_v3(df, list_sessionMarker,
                      trialStartMarker, trialHitMarker,
                      trialMissMarker, sessionStartMarker,
                      trialProbMarker, rewardProbMarker,
                      lickMarker, animal)

# if you want to add block numbers, uncomment this section
# sessdf['sess_block'] = 0
# thing = sessdf.groupby(['animal', 'task', 'session']).datetime.head(1).astype('datetime64[ns]').diff().dt.seconds>2400
# sessdf.loc[thing[thing == True].index, 'sess_block'] = 1
# sessdf['sess_block'] = sessdf.groupby(['animal', 'task']).sess_block.cumsum()

['Giratina-2025-03-05-19-27-27.dat', 'Giratina-2025-03-06-19-27-27.dat', 'Giratina-2025-03-07-19-27-27.dat', 'Giratina-2025-03-08-19-27-27.dat', 'Giratina-2025-03-09-19-27-27.dat', 'Giratina-2025-03-10-19-27-27.dat', 'Giratina-2025-03-11-19-27-27.dat', 'Giratina-2025-03-12-19-27-27.dat', 'Giratina-2025-03-13-19-27-27.dat', 'Giratina-2025-03-14-19-27-27.dat', 'Giratina-2025-03-15-19-27-27.dat', 'Giratina-2025-03-16-19-27-27.dat']

,trial,trialstart,port,reward,trialend,session,rewprob,eptime,task,rewprobfull,animal,datetime
0,0,20542.0,3.0,0.0,24734.0,1,15.0,1.741216e+09,13.0,[80 46 15 46],22,2025-03-05 23:00:31
1,1,27579.0,4.0,1.0,28435.0,1,46.0,1.741216e+09,13.0,[80 46 15 46],22,2025-03-05 23:00:38
2,2,33326.0,2.0,0.0,33890.0,1,46.0,1.741216e+09,13.0,[80 46 15 46],22,2025-03-05 23:00:44
3,3,36104.0,2.0,1.0,36680.0,1,46.0,1.741216e+09,13.0,[80 46 15 46],22,2025-03-05 23:00:47
4,4,39826.0,3.0,0.0,40326.0,1,15.0,1.741216e+09,13.0,[80 46 15 46],22,2025-03-05 23:00:51
...,...,...,...,...,...,...,...,...,...,...,...,...
29826,29826,99004.0,4.0,1.0,99504.0,167,46.0,1.742240e+09,13.0,[10 80 15 46],22,2025-03-17 19:27:18
29827,29827,101135.0,4.0,1.0,101635.0,167,46.0,1.742240e+09,13.0,[10 80 15 46],22,2025-03-17 19:27:20
29828,29828,103281.0,4.0,0.0,104067.0,167,46.0,1.742240e+09,13.0,[10 80 15 46],22,2025-03-17 19:27:23
29829,29829,104813.0,4.0,0.0,105324.0,167,46.0,1.742240e+09,13.0,[10 80 15 46],22,2025-03-17 19:27:24
29830,29830,106078.0,3.0,NaN,NaN,167,NaN,1.742240e+09,13.0,[10 80 15 46],22,2025-03-17 19:27:25

## ignore this section, untested

In [ ]:
from utils.opconNosepokeFunctions import *

animal = 'Xerneas'
date = '2026-01-10'
# end_date = '2026-01-05'
path = f"L:/4portProb_ephys/Box1_ephys/{animal}/Behavior/"      # for ephys only

files = exclude_files(get_files(path))
set_cwd(path)
files = [file for file in files if (file >=f'{animal}-{date}*.dat')]#& (file <= f'{animal}-{end_date}*.dat')]


files.sort()
print(files)

df = merge_files_to_df(files)

trialStartMarker = 81
trialHitMarker = 51
trialMissMarker = 86
trialProbMarker = 88
rewardProbMarker = 83
blockStartMarker = 61
blockEndMarker = 62
list_sessionMarker = [12, 13]
list_pokeMarker = [21, 20, 17, 37, 19, 18]
dict_port_rel = {
    1:[21],
    2:[20],
    3:[17, 19],
    4:[37, 18]
}
list_lickMarker = [24, 25, 22]

def trializer_temp(df, trialStartMarker, trialHitMarker, trialMissMarker, trialProbMarker, rewardProbMarker, blockStartMarker, blockEndMarker, list_sessionMarker, list_pokeMarker, list_lickMarker, dict_port_rel):
    sess_list = []
    data = df.to_numpy()
    # filter by useful events
    useful_events = [
        trialStartMarker, trialHitMarker, trialMissMarker,
        blockStartMarker, blockEndMarker,
        trialProbMarker, rewardProbMarker
        ] + list_pokeMarker + list_lickMarker

    useful_events = np.array(useful_events)

    # select useful data (correct events and state machines only)
    useful_mask = np.isin(data[:, 0], useful_events) & np.isin(data[:, 2], list_sessionMarker)
    useful_data = data[useful_mask]

    # extract trial info from useful_data, including how many trials
    trial_idx = np.where(useful_data[:, 0] == trialStartMarker)[0]

    # create arrays for all info in the trialStartMarker row
    port = useful_data[trial_idx, 1]
    sm = useful_data[trial_idx, 2]
    trial_start = useful_data[trial_idx, 4]
    trial_datetime = useful_data[trial_idx, 5]

    # when do the blocks/sessions change?
    block_start_idx = np.where(useful_data[:, 0] == blockStartMarker)[0]
    block_end_idx = np.where(useful_data[:, 0] == blockEndMarker)[0]
    block_num = 0

    # subset of used data
    event_col = useful_data[:, 0]
    value_col = useful_data[:, 1]
    time_col = useful_data[:, 4]
    cached_block_num = -1

    # Precompute poke event indices for each possible poke event -- this is supposed to be faster apparently
    # basically find all poke indices
    poke_event_indices = {poke: np.flatnonzero(event_col == poke) for poke in set(sum(dict_port_rel.values(), []))}

    # Precompute lick event indices for each lick marker -- this is supposed to be faster apparently
    lick_event_indices = {lick: np.flatnonzero(event_col == lick) for lick in list_lickMarker}

    # reward indices
    outcome_indices = {outcome: np.flatnonzero(event_col == outcome) for outcome in [trialHitMarker, trialMissMarker]}

    for t, idx in enumerate(trial_idx):
        # extract all info from before trialStartMarker row
        # potential info: poke in time, rewprob of session

        if block_num >= len(block_start_idx) or block_num >= len(block_end_idx):
            break

        # dont do this for every trial. only when blockStartMarker was passed
        if (idx>block_start_idx[block_num]) & (idx<block_end_idx[block_num]):
            
            # now that we are [in] a block, get all relevant info of the block
            if cached_block_num != block_num:
                block_data = useful_data[block_start_idx[block_num]:block_end_idx[block_num]+1]
                rewprob = block_data[block_data[:, 0] == rewardProbMarker][:, 4]

                # just in case things are jumbled
                rewprob_sorting = block_data[block_data[:, 0] == rewardProbMarker][:, 1]
                rewprob = rewprob[rewprob_sorting.astype(int)-1]
                cached_block_num = block_num

            # before trialStartMarker was detected
            # last nosepoke detected
            possible_pokes = dict_port_rel[port[t]]
            last_poke_idx = -1
            last_poke_time = np.nan
            poke_detected = None
            for poke in possible_pokes:
                inds = poke_event_indices[poke]
                inds_before = inds[inds <= idx]
                if inds_before.size > 0:
                    if inds_before[-1] > last_poke_idx:
                        last_poke_idx = inds_before[-1]
                        poke_detected = poke
                        last_poke_time = time_col[last_poke_idx]
            if last_poke_idx == -1:
                continue
            poke_in_time = last_poke_time

            # after trialStartMarker was detected
            # get poke out time
            inds_after = poke_event_indices[poke_detected]
            inds_after = inds_after[inds_after >= idx]
            if inds_after.size == 0:
                continue
            poke_out_time = time_col[inds_after[0]]

            # get appropriate lick marker
            # if there is no 25, use 22 or 24
            event_after = event_col[idx:]
            if np.any(event_after == 25):
                lickMarker = 25
            elif np.any(event_after == 24):
                lickMarker = 24
            else:
                lickMarker = 22
            
            # get first lick time
            lick_inds = lick_event_indices[lickMarker]
            lick_inds_first = lick_inds[lick_inds >= (idx-1 if idx > 0 else idx)]
            if lick_inds_first.size == 0:
                first_lick_time = np.nan
            else:
                first_lick_time = time_col[lick_inds_first[0]]

            # get last lick time: little tricky because you need everything until the next trial
            # but how to get next_idx?
            next_idx = trial_idx[t+1] if (t+1) < len(trial_idx) else len(useful_data)
            lick_inds_last = lick_inds[(lick_inds >= idx) & (lick_inds < next_idx)]

            if lick_inds_last.size == 0:
                # if no lick found within current trial window, fallback to any lick after trial start
                # lick_inds_fallback = lick_inds[lick_inds >= (idx-1 if idx > 0 else idx)]
                # if lick_inds_fallback.size == 0:
                #     last_lick_time = np.nan
                # else:
                #     last_lick_time = time_col[lick_inds_fallback[-1]]
                last_lick_time = np.nan
            else:
                last_lick_time = time_col[lick_inds_last[-1]]

            # get outcome info, finally
            hit_locs = np.flatnonzero(event_after == trialHitMarker)
            miss_locs = np.flatnonzero(event_after == trialMissMarker)
            if hit_locs.size == 0 and miss_locs.size == 0:
                outcome = np.nan
            elif hit_locs.size == 0:
                outcome = 0
            elif miss_locs.size == 0:
                outcome = 1
            else:
                outcome = int(hit_locs[0] < miss_locs[0])

            # get rewprob info on current trial
            trial_rewprob = value_col[idx:][event_after==trialProbMarker][0]   


        elif (idx>block_end_idx[block_num]):
            block_num += 1

        # convert rewprob to str
        rewprobl_str = str(np.array(rewprob, dtype = int))

        # get task info - str vs unstr
        task = sm[t]

        # append to sess_list
        sess_list.append([t, port[t], outcome, poke_in_time, poke_out_time, first_lick_time, last_lick_time, block_num, trial_rewprob, trial_datetime[t], task, rewprobl_str])  

    sessdf = pd.DataFrame(sess_list)
    return sessdf

sessdf = trializer_temp(df, trialStartMarker, trialHitMarker, trialMissMarker, trialProbMarker, rewardProbMarker, blockStartMarker, blockEndMarker, list_sessionMarker, list_pokeMarker, list_lickMarker, dict_port_rel)

['Xerneas-2026-01-10-19-58-37.dat', 'Xerneas-2026-01-11-19-58-37.dat', 'Xerneas-2026-01-12-19-02-16.dat', 'Xerneas-2026-01-12-19-32-57.dat', 'Xerneas-2026-01-13-19-32-57.dat', 'Xerneas-2026-01-14-17-35-44.dat', 'Xerneas-2026-01-14-18-01-26.dat', 'Xerneas-2026-01-14-18-05-08.dat', 'Xerneas-2026-01-14-18-20-40.dat', 'Xerneas-2026-01-14-18-31-47.dat', 'Xerneas-2026-01-15-10-19-23.dat', 'Xerneas-2026-01-16-10-19-23.dat', 'Xerneas-2026-01-17-10-19-23.dat', 'Xerneas-2026-01-18-10-19-23.dat', 'Xerneas-2026-01-19-10-19-23.dat', 'Xerneas-2026-01-20-10-19-23.dat', 'Xerneas-2026-01-21-10-19-23.dat', 'Xerneas-2026-01-22-10-19-23.dat', 'Xerneas-2026-01-23-10-19-23.dat', 'Xerneas-2026-01-24-10-19-23.dat', 'Xerneas-2026-01-25-10-19-23.dat', 'Xerneas-2026-01-26-20-04-35.dat', 'Xerneas-2026-01-27-20-04-35.dat', 'Xerneas-2026-01-28-20-04-35.dat', 'Xerneas-2026-01-29-20-04-35.dat', 'Xerneas-2026-01-30-20-04-35.dat', 'Xerneas-2026-01-31-20-04-35.dat', 'Xerneas-2026-02-01-20-04-35.dat', 'Xerneas-2026-02-02-20-04-35.dat', 'Xerneas-2026-02-03-20-04-35.dat', 'Xerneas-2026-02-04-20-04-35.dat', 'Xerneas-2026-02-05-20-04-35.dat', 'Xerneas-2026-02-06-20-04-35.dat', 'Xerneas-2026-02-07-20-04-35.dat', 'Xerneas-2026-02-08-20-04-35.dat', 'Xerneas-2026-02-09-20-04-35.dat', 'Xerneas-2026-02-10-20-04-35.dat', 'Xerneas-2026-02-11-20-04-35.dat', 'Xerneas-2026-02-12-20-04-36.dat', 'Xerneas-2026-02-13-20-04-36.dat', 'Xerneas-2026-02-14-20-04-36.dat', 'Xerneas-2026-02-15-20-04-36.dat', 'Xerneas-2026-02-16-20-04-36.dat', 'Xerneas-2026-02-17-20-04-36.dat', 'Xerneas-2026-02-18-20-04-36.dat', 'Xerneas-2026-02-19-20-04-37.dat', 'Xerneas-2026-02-20-20-04-37.dat', 'Xerneas-2026-02-21-20-04-37.dat', 'Xerneas-2026-02-22-20-04-37.dat', 'Xerneas-2026-02-23-20-04-37.dat']

c:\Users\dlab\banditAnalysis\utils\opconNosepokeFunctions.py:48: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(map(partial(pd.read_csv, header=None, names = names), files), ignore_index = True).dropna()

In [ ]:
sessdf

,0,1,2,3,4,5,6,7,8,9,10,11
0,0,1,0,7249,7362,9993,10289.0,0,10,1.768075e+09,13,[10 46 15 80]
1,1,2,0,11088,272336,13215,13521.0,0,46,1.768075e+09,13,[10 46 15 80]
2,2,2,1,11088,272336,16431,NaN,0,80,1.768075e+09,13,[10 46 15 80]
3,3,4,1,14433,14891,16431,19776.0,0,80,1.768075e+09,13,[10 46 15 80]
4,4,2,0,11088,272336,21779,NaN,0,80,1.768075e+09,13,[10 46 15 80]
...,...,...,...,...,...,...,...,...,...,...,...,...
73534,73534,1,1,307866,307911,308570,309986.0,374,80,1.770655e+09,13,[15 46 46 80 15 46 46 80 15 46 46 80 15 46 46 ...
73535,73535,1,1,310609,310781,311474,312846.0,374,80,1.770655e+09,13,[15 46 46 80 15 46 46 80 15 46 46 80 15 46 46 ...
73536,73536,1,1,313699,313736,314451,2582.0,374,80,1.770655e+09,13,[15 46 46 80 15 46 46 80 15 46 46 80 15 46 46 ...
73537,73537,1,1,313699,313736,314451,2582.0,375,80,1.770725e+09,13,[15 46 46 80 15 46 46 80 15 46 46 80 15 46 46 ...
73538,73538,2,1,313699,313736,314451,2582.0,376,80,1.770725e+09,13,[15 46 46 80 15 46 46 80 15 46 46 80 15 46 46 ...

In [ ]:
# Vectorized lick detection (use marker 25, fallback to 24, then 22)
n_trials = len(trial_idx)
trial_starts = trial_idx
trial_ends = np.append(trial_idx[1:], len(event_col))
ports = useful_data[trial_idx, 1].astype(int)
eptimes = useful_data[trial_idx, 5]
sm = useful_data[trial_idx, 2]

# Preallocate arrays
poke_in_times = np.full(n_trials, np.nan)
poke_out_times = np.full(n_trials, np.nan)
first_lick_times = np.full(n_trials, np.nan)
last_lick_times = np.full(n_trials, np.nan)
outcomes = np.full(n_trials, np.nan)
block_nums = np.zeros(n_trials, dtype=int)
trial_rewprobs = np.full(n_trials, np.nan)

# Vectorized block assignment
block_start_idx = np.where(event_col == 61)[0]
block_end_idx = np.where(event_col == 62)[0]
block_bins = np.searchsorted(block_end_idx, trial_starts, side='right')
block_nums[:] = block_bins

# Precompute poke event indices for all possible poke events
poke_event_indices = {poke: np.flatnonzero(event_col == poke) for poke in set(sum(dict_port_rel.values(), []))}

# get first lick, last lick times
lick_marker = None
if np.any(event_col == 25):
    lick_marker = 25
elif np.any(event_col == 24):
    lick_marker = 24
else:
    lick_marker = 22
lick_mask = (event_col == lick_marker)
lick_times = time_col[lick_mask]
lick_indices = np.flatnonzero(lick_mask)
first_lick_idx = np.searchsorted(lick_indices, trial_starts, side='left')
last_lick_idx = np.searchsorted(lick_indices, trial_ends, side='right') - 1
valid_first = (first_lick_idx < lick_indices.size)
first_lick_times[valid_first] = lick_times[first_lick_idx[valid_first]]
valid_last = (last_lick_idx >= 0) & (last_lick_idx < lick_indices.size)
last_lick_times[valid_last] = lick_times[last_lick_idx[valid_last]]

# outcome detection
hit_mask = (event_col == 51)
miss_mask = (event_col == 86)
hit_indices = np.flatnonzero(hit_mask)
miss_indices = np.flatnonzero(miss_mask)
for i, (start, end) in enumerate(zip(trial_starts, trial_ends)):
    first_hit = hit_indices[(hit_indices >= start) & (hit_indices < end)]
    first_miss = miss_indices[(miss_indices >= start) & (miss_indices < end)]
    if first_hit.size == 0 and first_miss.size == 0:
        outcomes[i] = np.nan
    elif first_hit.size == 0:
        outcomes[i] = 0
    elif first_miss.size == 0:
        outcomes[i] = 1
    else:
        outcomes[i] = int(first_hit[0] < first_miss[0])

# trial rewprob extraction
prob_mask = (event_col == 88)
for i, (start, end) in enumerate(zip(trial_starts, trial_ends)):
    prob_idx = np.flatnonzero(prob_mask[start:end])
    if prob_idx.size > 0:
        trial_rewprobs[i] = value_col[start:end][prob_idx[0]]

In [ ]:
import numpy as np
import pandas as pd

# def extract_trials_vectorized(useful_data, trial_idx, event_col, value_col, time_col, dict_port_rel):
    # """
    # Vectorized extraction of trial features for bandit analysis.
    # Returns a DataFrame with trial-wise features.
    # """
n_trials = len(trial_idx)
trial_starts = trial_idx
trial_ends = np.append(trial_idx[1:], len(event_col))
ports = useful_data[trial_idx, 1].astype(int)
eptimes = useful_data[trial_idx, 5]
sm = useful_data[trial_idx, 2]

# Preallocate arrays
poke_in_times = np.full(n_trials, np.nan)
poke_out_times = np.full(n_trials, np.nan)
first_lick_times = np.full(n_trials, np.nan)
last_lick_times = np.full(n_trials, np.nan)
outcomes = np.full(n_trials, np.nan)
block_nums = np.zeros(n_trials, dtype=int)
trial_rewprobs = np.full(n_trials, np.nan)

# Vectorized block assignment
block_start_idx = np.where(event_col == 61)[0]
block_end_idx = np.where(event_col == 62)[0]
block_bins = np.searchsorted(block_end_idx, trial_starts, side='right')
block_nums[:] = block_bins

# Precompute poke event indices for all possible poke events
poke_event_indices = {poke: np.flatnonzero(event_col == poke) for poke in set(sum(dict_port_rel.values(), []))}

# Vectorized poke in time (last poke before trial start)
for port_num, poke_codes in dict_port_rel.items():
    trial_mask = (ports == port_num)
    trial_starts_port = trial_starts[trial_mask]
    if trial_starts_port.size == 0:
        continue
    poke_inds = np.concatenate([poke_event_indices[code] for code in poke_codes if code in poke_event_indices])
    if poke_inds.size == 0:
        continue
    poke_inds.sort()
    last_poke_idx = np.searchsorted(poke_inds, trial_starts_port, side='right') - 1
    valid = (last_poke_idx >= 0) & (last_poke_idx < poke_inds.size)
    poke_in_times_for_port = np.full(trial_mask.sum(), np.nan)
    poke_in_times_for_port[valid] = time_col[poke_inds[last_poke_idx[valid]]]
    poke_in_times[trial_mask] = poke_in_times_for_port

# Vectorized poke out time (first poke after trial start)
for port_num, poke_codes in dict_port_rel.items():
    trial_mask = (ports == port_num)
    trial_starts_port = trial_starts[trial_mask]
    if trial_starts_port.size == 0:
        continue
    poke_inds = np.concatenate([poke_event_indices[code] for code in poke_codes if code in poke_event_indices])
    if poke_inds.size == 0:
        continue
    poke_inds.sort()
    insert_pos = np.searchsorted(poke_inds, trial_starts_port, side='left')
    valid = (insert_pos < poke_inds.size)
    poke_out_times_for_port = np.full(trial_mask.sum(), np.nan)
    poke_out_times_for_port[valid] = time_col[poke_inds[insert_pos[valid]]]
    poke_out_times[trial_mask] = poke_out_times_for_port

# Vectorized lick detection (use marker 25, fallback to 24, then 22)
lick_marker = None
if np.any(event_col == 25):
    lick_marker = 25
elif np.any(event_col == 24):
    lick_marker = 24
else:
    lick_marker = 22
lick_mask = (event_col == lick_marker)
lick_times = time_col[lick_mask]
lick_indices = np.flatnonzero(lick_mask)
first_lick_idx = np.searchsorted(lick_indices, trial_starts, side='left')
last_lick_idx = np.searchsorted(lick_indices, trial_ends, side='right') - 1
valid_first = (first_lick_idx < lick_indices.size)
first_lick_times[valid_first] = lick_times[first_lick_idx[valid_first]]
valid_last = (last_lick_idx >= 0) & (last_lick_idx < lick_indices.size)
last_lick_times[valid_last] = lick_times[last_lick_idx[valid_last]]

# Vectorized outcome detection
hit_mask = (event_col == 51)
miss_mask = (event_col == 86)
hit_indices = np.flatnonzero(hit_mask)
miss_indices = np.flatnonzero(miss_mask)
for i, (start, end) in enumerate(zip(trial_starts, trial_ends)):
    first_hit = hit_indices[(hit_indices >= start) & (hit_indices < end)]
    first_miss = miss_indices[(miss_indices >= start) & (miss_indices < end)]
    if first_hit.size == 0 and first_miss.size == 0:
        outcomes[i] = np.nan
    elif first_hit.size == 0:
        outcomes[i] = 0
    elif first_miss.size == 0:
        outcomes[i] = 1
    else:
        outcomes[i] = int(first_hit[0] < first_miss[0])

# Vectorized trial rewprob extraction
prob_mask = (event_col == 88)
for i, (start, end) in enumerate(zip(trial_starts, trial_ends)):
    prob_idx = np.flatnonzero(prob_mask[start:end])
    if prob_idx.size > 0:
        trial_rewprobs[i] = value_col[start:end][prob_idx[0]]

# get rewprobs for blocks
# Vectorized rewprobfull assignment
    # Precompute reward probability string for each block
block_count = max(block_nums) + 1
block_rewprob_strs = np.empty(block_count, dtype=object)
for block in range(block_count):
    if block < len(block_start_idx) and block < len(block_end_idx):
        start = block_start_idx[block]
        end = block_end_idx[block] + 1
        block_data = useful_data[start:end]
        rewprob_events = block_data[block_data[:, 0] == 83]
        if rewprob_events.shape[0] > 0:
            ports_in_block = rewprob_events[:, 1].astype(int)
            values_in_block = rewprob_events[:, 4].astype(int)
            sorted_indices = np.argsort(ports_in_block)
            sorted_values = values_in_block[sorted_indices]
            block_rewprob_strs[block] = str(sorted_values)
        else:
            block_rewprob_strs[block] = ''
    else:
        block_rewprob_strs[block] = ''
rewprobfull = block_rewprob_strs[block_nums]

# Assemble DataFrame
sessdf_vec = pd.DataFrame({
    'trial': np.arange(n_trials),
    'port': ports,
    'outcome': outcomes,
    'poke_in_time': poke_in_times,
    'poke_out_time': poke_out_times,
    'first_lick_time': first_lick_times,
    'last_lick_time': last_lick_times,
    'block_num': block_nums,
    'trial_rewprob': trial_rewprobs,
    'eptime':eptimes,
    'task':sm,
    'rewprob': rewprobfull
})
    # return sessdf_vec

In [ ]:
(sessdf_vec.outcome==pd.DataFrame(sess_list, columns = sessdf_vec.columns).outcome).sum

0        True
1        True
2        True
3        True
4        True
         ...
46577    True
46578    True
46579    True
46580    True
46581    True
Name: outcome, Length: 46582, dtype: bool

:

In [ ]:
def trializer_v3(df, list_sessionMarker,
                 trialStartMarker, trialHitMarker,
                 trialMissMarker, sessionStartMarker,
                 trialProbMarker, rewardProbMarker, lickMarker, animal, arms = 4):
    
    ''' Function to convert a df of joined .dat files with column names in order :
    'event', 'value', 'sm', 'tp', 'smtime', 'eptime', 'dw', 'ww'
    
    INPUTS: df, list of session state machine numbers, trial start marker, trial rewarded marker,
    trial miss/unrewarded marker, session start marker, trial probability marker, session reward prob marker, 
    animal name, num arms in task
    
    OUTPUT: single trial-wise dataframe of one animal
    2023-10-26
    '''
    # initialize var
    sessnum = 0
    npcounter = 0
    sess_list = []
    rewprobl = []

    event_lookup = {
        trialHitMarker: 1,
        trialMissMarker: 0,
    }
    list_events = [trialStartMarker, trialHitMarker, trialMissMarker, trialProbMarker, sessionStartMarker,
                   trialProbMarker, rewardProbMarker, lickMarker]

    # filter events as np array to increase speed and avoid repetitive indexing
    filtered_events = df[(df['sm'].isin(list_sessionMarker)) & (df['event'].isin(list_events))].to_numpy()
    indices = np.where((filtered_events[:, 0] == trialStartMarker) | (filtered_events[:, 0]==sessionStartMarker) | (filtered_events[:, 0]==rewardProbMarker))[0]

    for ind in indices:
        # extract information from the current trialStartMarker
        trialstart = filtered_events[ind, 4]
        port = filtered_events[ind, 1]
        datetime = filtered_events[ind, 5]
        task = filtered_events[ind, 2]
        event = filtered_events[ind, 0]

        # select events occurring after/before trialStartMarker
        nextEvents = filtered_events[ind:]
        # prevEvents = filtered_events[:ind]

        try:
            # find the index of trialMissMarker or trialHitMarker in nextEvents
            status_indices = np.where(
                (nextEvents[:, 0] == trialMissMarker) | (nextEvents[:, 0] == trialHitMarker)
                )[0]
            if status_indices.size > 0:
                trial_outcome_index = status_indices[0] 
            else: 
                trial_outcome_index = None

            # find the index of trialProbMarker in nextEvents
            rewprob_index = np.where(nextEvents[:, 0] == trialProbMarker)[0][0] 
            #contLine: if np.any(nextEvents[:, 0] == trialProbMarker) else None

            # find the index of poke out in nextEvents
            pokeout_index = np.where((nextEvents[:, 0] == port) & (nextEvents[:, 1] == 0))[0][0]

            if trial_outcome_index is not None:
                # find reward, trialend, and rewprob based on identified events
                reward = event_lookup[nextEvents[trial_outcome_index, 0]]
                trialend = nextEvents[trial_outcome_index, 4]
                if rewprob_index is not None:
                    rewprob = nextEvents[rewprob_index, 1]
                else:
                    rewprob = np.nan
            else:
                # if trialMissMarker or trialHitMarker not found, nan
                reward = np.nan
                trialend = np.nan
                rewprob = np.nan
        except IndexError:
            # set values to nan in case of issues
            reward = np.nan
            trialend = np.nan
            rewprob = np.nan

        # get poke in and poke out times


        rewprobl_str = str(np.array(rewprobl, dtype = int))
        # append to sess_list
        sess_list.append([npcounter, trialstart, port, reward, trialend, sessnum, rewprob, datetime, task, event, rewprobl_str])
        npcounter += 1

        if filtered_events[ind, 0] == sessionStartMarker:
            # update session number when sessionStartMarker found
            rewprobl = []
            sessnum +=1

        if filtered_events[ind, 0] == rewardProbMarker:
            rewprobl.append(filtered_events[ind, 4])

    # create pandas dataframe from the list of all session data
    sessdf =  pd.DataFrame(sess_list, columns = ['trial', 'trialstart',
                                   'port', 'reward', 'trialend',
                                   'session', 'rewprob', 'eptime', 'task', 'event', 'rewprobfull'])

    # remove all lines corresponding to start of a session or reward prob marker
    sessdf = sessdf[(sessdf.event!=sessionStartMarker) & (sessdf.event!=rewardProbMarker)].reset_index(drop = True).drop(columns = 'event')

    # remove all lines that have (trialend-trialstart)> 5500 or negative (sum of tone + wait time)
    # is this check required?

    # reset trial numbers
    sessdf['trial'] = np.arange(len(sessdf))

    # add animal information
    sessdf['animal'] = animal
    
    # add datetime
    sessdf['datetime'] = pd.to_datetime(sessdf.eptime, unit='s')

    return sessdf

In [ ]:
### exclude files if required, by expression
# default: exclude_files(files, exclusion=['Roselia.+.dat', 'test-2022.+.dat', 'test-2023.+.dat', 'Azurill.+.dat'])
# animal = 'Bayleef'
# box = 7
# date = '2024-08-04'

# files = exclude_files(get_files(f"L:/4portProb/Box{box}/{animal}/"))
# files = [file for file in files if (file >=f'{animal}-{date}*.dat')]
# files.sort()
# list_sessionMarker = [12, 13]

# df = merge_files_to_df(files)
# sessdf = trializer_v3(df, list_sessionMarker,
#                       trialStartMarker, trialHitMarker,
#                       trialMissMarker, sessionStartMarker,
#                       trialProbMarker, rewardProbMarker, animal)
sessdf.task = sessdf.task.replace({13:'unstr', 12:'str'})
# reducing filesize on disk
sessdf["animal"] = sessdf["animal"].astype("category")
sessdf["task"] = sessdf['task'].astype("category")
# sessdf["rewprobfull"] = sessdf['rewprobfull'].astype(str).astype("category")

In [ ]:
# check which sms on this day
stateMachines = np.sort(df['sm'].unique())
print(stateMachines)
SMlist = ['DailyWater0', 'WeeklyWater1', 'HouseLightsOn2', 'HouseLightsOff3', 'HouseLightsOnToneWater4',
           'BlinkLightsToneWater5', 'NosepokeNonSession6', 'LickTest7', 'LickTrain8', 'Nosepoke2sound9','Nosepoke1sound10',
          'NosepokeProb7011', 'NosepokeStr12', 'NosepokeUNStr13', 'NosepokeProb4014','ReadSessionParams15','NosepokeNonSession216','DoNothing17']
# session_rew_daily=(max(df[(df[2]<11) & (df[2]>6)][6]) - min(df[(df[2]<11) & (df[2]>6)][6]))
# non_session_rew_daily=max(df[df[2].isin([6,14])][6])-min(df[df[2].isin([6,14])][6])
# print('max day reward from sessions =', session_rew_daily)
# print('max day reward from non-session =',non_session_rew_daily)
# print('total reward through np =', session_rew_daily+non_session_rew_daily)

[ 0  1  2  3  4  5  7  9 10 11 13 17]

In [ ]:
sessdf

,trial,trialstart,port,reward,trialend,session,rewprob,eptime,task,rewprobfull,animal,datetime
0,0,1646.0,3.0,1.0,2497.0,1,80.0,1.768173e+09,13.0,[15 46 80 10],22,2026-01-11 23:16:26
1,1,3668.0,2.0,0.0,4349.0,1,46.0,1.768173e+09,13.0,[15 46 80 10],22,2026-01-11 23:16:28
2,2,4805.0,2.0,1.0,5581.0,1,46.0,1.768173e+09,13.0,[15 46 80 10],22,2026-01-11 23:16:29
3,3,6742.0,3.0,0.0,7373.0,1,80.0,1.768173e+09,13.0,[15 46 80 10],22,2026-01-11 23:16:31
4,4,8061.0,2.0,1.0,8668.0,1,46.0,1.768173e+09,13.0,[15 46 80 10],22,2026-01-11 23:16:32
...,...,...,...,...,...,...,...,...,...,...,...,...
859,859,431428.0,3.0,0.0,432614.0,6,15.0,1.768189e+09,13.0,[10 80 15 46],22,2026-01-12 03:38:20
860,860,434170.0,3.0,0.0,436212.0,6,15.0,1.768189e+09,13.0,[10 80 15 46],22,2026-01-12 03:38:23
861,861,443964.0,3.0,1.0,445319.0,6,15.0,1.768189e+09,13.0,[10 80 15 46],22,2026-01-12 03:38:33
862,862,451383.0,2.0,1.0,453600.0,6,80.0,1.768189e+09,13.0,[10 80 15 46],22,2026-01-12 03:38:40
863,863,457375.0,3.0,0.0,462876.0,6,15.0,1.768189e+09,13.0,[10 80 15 46],22,2026-01-12 03:38:46

# Nosepoke session analysis

In [12]:
# %matplotlib nbagg
# this plots blockwise raster of choice
%matplotlib qt

import ipywidgets as widgets
from IPython.display import display
from matplotlib.patches import Rectangle
from utils.plotSettings import *
# import matplotlib.pyplot as plt
import seaborn as sns


# Create a function to update the plot based on user input
def update_plot(session_range):
    sessdf_filtered = sessdf[sessdf['session'].between(*session_range)]
    markers = {0: "$o$", 1: "o"}   # for reward-wise raster, useful for initial stages or zooming into data
#     markers = {0: 2, 1:3}
#     fig = plt.figure(figsize=(15, 8))
    g = sns.relplot(data=sessdf_filtered, y='port', x='trial', 
                    hue='rewprob',
                    aspect=11.7/5.5,
                    linewidth=0.75, s=100, palette = 'Blues', marker = '|', # change '|' to markers for reward-wise raster
                    # markers=markers, style='reward',
                    hue_norm=(-20, 80))
    axes = g.axes.flatten()
    last = sessdf.groupby('session')['trial'].max().to_list()
    start = sessdf.groupby('session')['trial'].min().to_list()
    highport = [ind+1 for i in sessdf.groupby('session').head(1).rewprobfull for ind, j in enumerate(i.strip('[]').split()) if j=='80']
    for ax in axes:
        for ind, l in enumerate(last):
            ax.axvline(l, linewidth=1, color='grey')
#             ax.axvline(, linewidth = 1, color = 'red')
            ax.set_yticks([1, 2, 3, 4])
            ax.add_patch(Rectangle((start[ind]-1, highport[ind]-0.5), l-start[ind], 1, fc = 'xkcd:blue', alpha = 0.1))
    
    plt.ylim(0.5, 4.5)
    plt.title('Choices', y=1.05)
    g._legend.set_title('Rew. %')
    # g._legend.texts[0].set_text("Reward %")
    # g._legend.texts[5].set_text("Outcome")
    plt.xticks(ticks = [], labels = [])

    plt.xlabel(' ', labelpad=20)
    plt.ylabel('Port')
    
    # Calculate x-axis limits based on the displayed sessions
    x_limit = (sessdf_filtered['trial'].min(), sessdf_filtered['trial'].max())
    plt.xlim(*x_limit)
    sns.despine(bottom = True)
#     plt.savefig('C:/Users/dlab/OneDrive - Indian Institute of Science/Drawings/plots/15012024/eg.svg', dpi = 600)
    plt.show()

# Define the session range using a widget
session_range_slider = widgets.IntRangeSlider(
    value=[sessdf['session'].min(), sessdf['session'].max()],
    min=sessdf['session'].min(),
    max=sessdf['session'].max(),
    step=1,
    description='Session Range:',
    continuous_update=False
)

# Create an interactive plot using interactive
interactive_plot = widgets.interactive(update_plot, session_range=session_range_slider)

# Display the interactive plot
display(interactive_plot)
plt.xticks(ticks = [], labels = [])
# plt.tight_layout()
# sns.set_context('talk')
# plt.title('Blissey - DLS then DMS lesion')

interactive(children=(IntRangeSlider(value=(1, 164), continuous_update=False, description='Session Range:', ma…

([], [])

In [ ]:
# check if there are any duplicated trials - this means there's something wrong with the box
mask = sessdf.duplicated(subset = ['animal', 'session', 'trialstart', 'trialend', 'eptime'], keep = False)
sessdf[mask]

Empty DataFrame
Columns: [trial, trialstart, port, reward, trialend, session, rewprob, eptime, task, rewprobfull, animal, datetime]
Index: []

In [11]:
#plot number of times each port was chosen/total trials in block as a function of rewprob at that port, for all trials indf; average across blocks
port_choices = [1, 2, 3, 4]
#group by unique rewprob values, find unique rewprob values across all ports first
colors_ports = ['red', 'green', 'blue', 'purple']
unique_rewprobs = np.unique(sessdf['rewprob'])
# print(unique_rewprobs)
#remove nan from unique_rewprobs
unique_rewprobs = unique_rewprobs[~np.isnan(unique_rewprobs)]
print(unique_rewprobs)
#remove rows with nan rewprob
sessdf = sessdf[~sessdf['rewprob'].isna()]

#for every block, calculate number of times each port was chosen/total trials in block for each unique rewprob value
nblocks = sessdf['session'].nunique()
port_choice_matrix = np.zeros((len(unique_rewprobs), len(port_choices), nblocks))
#for all blocks
#save all rewprobfull per block in a list
for block in range(1, sessdf['session'].nunique()+1):
    block_data = sessdf[sessdf['session'] == block]
    #for all ports
    for p, port in enumerate(port_choices):
        port_data = block_data[block_data['port'] == port]
        #for all unique rewprobs
        for r, rewprob in enumerate(unique_rewprobs):
            n_choices = len(port_data[port_data['rewprob'] == rewprob])
            port_choice_matrix[r, p, block-1] = n_choices

bias_matrix = np.zeros((port_choice_matrix.shape[0], port_choice_matrix.shape[1]))
counter = np.zeros((port_choice_matrix.shape[0], port_choice_matrix.shape[1]))

for p in range(port_choice_matrix.shape[1]):
    for r in range(port_choice_matrix.shape[0]):
        bias_matrix[r, p] = 0
        for b in range(port_choice_matrix.shape[2]):
            ntrls = np.sum(port_choice_matrix[:,:,b])
            if ntrls != 0:
                bias_matrix[r, p] += port_choice_matrix[r, p, b] / ntrls
            if port_choice_matrix[r, p, b] > 0:
                counter[r, p] += 1

#divide fin_mat by counter
for p in range(port_choice_matrix.shape[1]):
    for r in range(port_choice_matrix.shape[0]):
        if counter[r, p] > 0:
            bias_matrix[r, p] = bias_matrix[r, p] / counter[r, p]
print('Bias matrix:', bias_matrix)


#plot as line plots for each port
plt.figure(figsize=(7, 6))
for p, port in enumerate(port_choices):
    plt.plot([0,1,2,3], bias_matrix[:, p], label=f'Port {port}', marker='o', linewidth=2, color=colors_ports[p])
plt.xlabel('Reward Probability')
plt.xticks([0,1,2,3], labels=[int(r) for r in unique_rewprobs])
plt.ylabel(f'Fraction chosen (averaged across {nblocks} blocks)')
plt.title(f'{animal}')
plt.legend()
plt.show()

n_rows, n_cols = bias_matrix.shape
rpf = [10,15,46,80]
labels = [i+1 for i in range(n_cols)]

# Angles for radar
angles = np.linspace(0, 2*np.pi, n_cols, endpoint=False)
angles = np.concatenate([angles, [angles[0]]])  # close loop

fig, ax = plt.subplots(figsize=(6, 6), subplot_kw=dict(polar=True))
for i in range(n_rows):
    values = bias_matrix[i]
    values = np.concatenate([values, [values[0]]])  # close loop

    ax.plot(angles, values, linewidth=2, label=f'prob {rpf[i]}', color=colors_ports[i])
    # ax.fill(angles, values, alpha=0.15)

ax.set_thetagrids(np.degrees(angles[:-1]), labels)
#reduce the yticks to 3
# ax.set_yticks([])
ax.legend(loc='upper right', bbox_to_anchor=(1.25, 1.1))
plt.tight_layout()
plt.show()

[10. 15. 46. 80.]
Bias matrix: [[0.1134174  0.16624716 0.13970177 0.09237282]
 [0.25029183 0.19829389 0.2551206  0.03975422]
 [0.44720339 0.53411497 0.58340037 0.15105006]
 [0.55367452 0.46757464 0.71895848 0.25558881]]

In [ ]:
# add columns to make transition matrix
sessdf['choice_t1'] = sessdf.groupby(['animal','session']).port.shift(-1)
sessdf['choice_t2'] = sessdf.groupby(['animal','session']).port.shift(-2)
sessdf['shift_t0'] = (sessdf['choice_t1']==sessdf['port']).replace({True: 0, False: 1})
sessdf['shift_t1'] = (sessdf['choice_t2']==sessdf['port']).replace({True: 0, False: 1})

C:\Users\dlab\AppData\Local\Temp\ipykernel_16272\2834681967.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  sessdf['shift_t0'] = (sessdf['choice_t1']==sessdf['port']).replace({True: 0, False: 1})
C:\Users\dlab\AppData\Local\Temp\ipykernel_16272\2834681967.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  sessdf['shift_t1'] = (sessdf['choice_t2']==sessdf['port']).replace({True: 0, False: 1})

In [ ]:
import matplotlib.pyplot as plt
plt.figure()
set_cwd('C:/Users/dlab/rishika_sim')
from utils.plotSettings import *
parula = get_parula_cmap()

ax = plt.subplot(111)
ratdf = sessdf[ ~(sessdf.duplicated(subset = ['animal', 'session', 'trialstart', 'trialend', 'eptime'], keep = False))]
# raltzdf = raltzdf.groupby('session').filter(lambda x: x.reward.size >= trialsinsess).groupby('session').head(trialsinsess)
sns.heatmap(pd.crosstab(ratdf.port, ratdf.choice_t1, normalize = 'index'), 
            ax = ax,
            cmap = parula,
            annot = True,
            fmt = '.2f',
            vmin = 0.0,
            vmax = 0.1,
            square = True,
            # mask = np.eye(4),
            xticklabels = np.arange(1,5), yticklabels = np.arange(1,5))
# ax.patch.set_facecolor('white')
ax.set_xlabel('Choice at trial t+1', fontsize = 'x-large')
ax.set_ylabel('Choice at trial t', fontsize = 'x-large')
ax.tick_params(axis = u'both', which = u'both', length = 0, labelsize = 'large', color = 'grey')

In [ ]:
# plot reward rate / regret
window = 5
sessdf['rr'] = sessdf.groupby('session', as_index = False).reward.rolling(window, center=True).mean().reward
sessdf['regret'] = abs(sessdf['rewprob']-80)
ax= plt.subplot(111)
rr_mean_dict = {}
trialsinsess = 100
filtered = (sessdf.groupby('session')).filter(lambda x: x.reward.size >= trialsinsess)

# take only those sessions
filtered = filtered.groupby('session').head(trialsinsess)


# convert to numpy array
g = filtered.groupby('session').cumcount()
L = np.array(filtered.set_index(['session',g])
    .unstack(fill_value=0)
    .stack(future_stack = True).groupby(level=0)
    .apply(lambda x: x.rr.to_numpy())
    .to_numpy())

# mean
rr_mean = np.mean(L, axis=0)
# rr_mean_dict[animal] = rr_mean
ax.plot(rr_mean)#, label = i, c = colors[i])
sns.despine()
ax.set_xlabel('Trials')
ax.set_ylabel('Reward rate')
plt.tight_layout()

In [ ]:
# bias analysis - this needs to be changed, a la last group meeting (normalize differently)
# set_cwd('/home/rishika/sim/')
# from supplementaryFunctions import *
%matplotlib qt
trialsinsess = 100
# new_unstr_sess_dict = loader('new_unstructured')
# sessdf = new_unstr_sess_dict['/home/rishika/sim/NAS_rishika/4portProb/Box2']
fig = plt.figure(figsize = (8,7))
ax = plt.subplot(111)
filtered = sessdf[~(sessdf.duplicated(subset = ['animal', 'session', 'trialstart', 'trialend', 'eptime'], keep = False))].groupby('session').filter(lambda x: x.reward.size >= trialsinsess)
# take only those sessions
filtered = filtered.groupby('session').head(trialsinsess)

# Precompute choice probabilities
session_sizes = filtered.groupby('session').size()
choice_data = []
for i in range(1, 5):
    port_data = filtered[filtered['port'] == i].groupby(['session', 'rewprob']).size().reset_index(name='count')
    port_data['choice_prob'] = port_data['count'] / port_data['session'].map(session_sizes)
    port_data['port'] = i
    choice_data.append(port_data)
choice_df = pd.concat(choice_data, ignore_index=True)

# Plot
for i in range(1, 5):
    port_df = choice_df[choice_df['port'] == i]
    sns.scatterplot(data=port_df, x='rewprob', y='choice_prob', alpha=0.1, ax=ax)
    mean_df = port_df.groupby('rewprob')['choice_prob'].mean().reset_index()
    sns.lineplot(data=mean_df, x='rewprob', y='choice_prob', ax=ax, linewidth=2, label=f'Port {i}')

ax.set_ylabel('choice probability')
ax.set_xlabel('reward percent')
sns.despine()
ax.legend()
plt.suptitle(f'Choice Probability vs. Reward Percent, per arm, animal = {animal}')
plt.tight_layout()
plt.show()

In [ ]:
# reward collection latency
g = sns.relplot(data=sessdf, x=sessdf['trialend']-sessdf['trialstart'], y='trial', hue='reward')
axes = g.axes.flatten()

# find the last trial number of a session
last = sessdf.groupby('session')['trial'].max()
for ax in axes:
    for l in last:
        ax.axhline(l, linewidth = 0.7, color='grey')
        ax.set_xlabel('Latency (ms)')
        ax.set_xlim(0,5600)
        ax.set_ylim(bottom=-5)
sns.set_context('notebook')
plt.suptitle('Latency', y=1.05)
# plt.savefig('plots/25082023/dms_D03_latency.png', dpi = 300)

Text(0.5, 1.05, 'Latency')

In [ ]:
# number of trials in each session
g = sns.relplot(data=sessdf['session'].value_counts(), kind='scatter', color='k')
g.set_xlabels('session')
g.set_ylabels('# of trials')
# for ax in g.axes.flat:
#     for i in sessdf['session']:
#         if i%3==0:
#             ax.axvline(x=i, color='xkcd:light grey', linestyle='-.')
plt.axhline(np.mean(sessdf['session'].value_counts()), c='r')
# plt.savefig('plots/25082023/dms_D03_numtrials.png', dpi = 300)

C:\Users\dlab\miniforge3\envs\rishika\lib\site-packages\seaborn\axisgrid.py:118: UserWarning: The figure layout has changed to tight
  self._figure.tight_layout(*args, **kwargs)

## old plots that may not mean anything

In [ ]:
###### plot cumulative regret 
g = sns.relplot(data = sessdf, x = 'trial', y = np.cumsum(sessdf.regret), color = 'k', kind = 'line')
# find the last trial number of a session
last = sessdf.groupby('session')['trial'].max()
for ax in g.axes.flat:
    for l in last:
        ax.axvline(l, linewidth = 1, color='grey')
ax.set_ylabel('cumulative regret')

Text(-21.30555555555555, 0.5, 'cumulative regret')

In [ ]:
# what is distance moved given last trial was not rewarded?
dist = []
dist_unrew = []
dist_rew = []
for i in range(len(sessdf)):
    if i+1<len(sessdf):
        if sessdf['reward'][i]==0:
            dist_unrew.append(sessdf['port'][i]-sessdf['port'][i+1])
        else:
            dist_rew.append(sessdf['port'][i]-sessdf['port'][i+1])
plt.plot(dist_unrew, 'k')
sns.despine()
# plt.plot(dist_rew, 'r')

# whismur special

In [ ]:
sessdf['blox_status'] = ''
sessdf.loc[(sessdf.datetime >= pd.to_datetime('20260112')) & (sessdf.datetime < pd.to_datetime('20260116')), 'blox_status'] = '2_blocked'
sessdf.loc[(sessdf.datetime >= pd.to_datetime('20260116')) & (sessdf.datetime < pd.to_datetime('20260129')), 'blox_status'] = 'unblocked'
sessdf.loc[(sessdf.datetime >= pd.to_datetime('20260130')) & (sessdf.datetime < pd.to_datetime('20260205')), 'blox_status'] = '23_blocked'
sessdf.loc[(sessdf.datetime >= pd.to_datetime('20260206')), 'blox_status'] = '14_blocked'
sessdf['transition_val'] = sessdf['port'].astype(str).apply(lambda x: x.split('.')[0]) + sessdf['choice_t1'].astype(str).apply(lambda x: x.split('.')[0])

In [ ]:
# 2_blocked switch rate - 1 to 2 vs 1 to 4
from utils.plotSettings import *
parula = get_parula_cmap()
plt.figure()
ax = plt.subplot(221)
empty_cell_val = np.nan
normalizing = 'all'
# empty_cell_val = 0

two_blocked_mask = (sessdf.blox_status == '2_blocked') & ~(sessdf.transition_val.isin(['1nan', '2nan', '3nan', '4nan']))
# add nan row with port 2 in the matrix
two_blocked_tm = pd.crosstab(sessdf[two_blocked_mask].port, sessdf[two_blocked_mask].choice_t1, normalize = normalizing).to_numpy()
two_blocked_tm = np.concatenate([two_blocked_tm[:, :-2], np.ones((3, 1))*empty_cell_val, two_blocked_tm[:, 1:]], axis = 1)
two_blocked_tm = np.concatenate([two_blocked_tm[:-2, :], np.ones((1,4))*empty_cell_val, two_blocked_tm[1:, :]], axis = 0)
sns.heatmap(two_blocked_tm, cmap = parula, vmax = 0.15, vmin = 0, ax = ax, square = True, xticklabels = np.arange(1,5), yticklabels = np.arange(1,5))
ax.set_title('2 blocked')

ax = plt.subplot(222)
unblocked_mask = (sessdf.blox_status == 'unblocked') & ~(sessdf.transition_val.isin(['1nan', '2nan', '3nan', '4nan']))
unblocked_tm = pd.crosstab(sessdf[unblocked_mask].port, sessdf[unblocked_mask].choice_t1, normalize = normalizing)
sns.heatmap(unblocked_tm, cmap = parula, vmax = 0.15, vmin = 0, ax = ax, square = True, xticklabels = np.arange(1,5), yticklabels = np.arange(1,5))
ax.set_title('unblocked')

ax = plt.subplot(223)
centre_blocked_mask = (sessdf.blox_status == '23_blocked') & ~(sessdf.transition_val.isin(['1nan', '2nan', '3nan', '4nan']))
centre_blocked_tm = pd.crosstab(sessdf[centre_blocked_mask].port, sessdf[centre_blocked_mask].choice_t1, normalize = normalizing)#.to_numpy()
centre_blocked_tm[2] = empty_cell_val
centre_blocked_tm[3] = empty_cell_val
centre_blocked_tm.loc[2] = empty_cell_val
centre_blocked_tm.loc[3] = empty_cell_val
centre_blocked_tm = centre_blocked_tm.sort_index()[[1,2,3,4]]
sns.heatmap(centre_blocked_tm, cmap = parula, vmax = 0.15, vmin = 0, ax = ax, square = True, xticklabels = np.arange(1,5), yticklabels = np.arange(1,5))
ax.set_title('2,3 blocked')

ax = plt.subplot(224)
edge_blocked_mask = (sessdf.blox_status == '14_blocked') & ~(sessdf.transition_val.isin(['1nan', '2nan', '3nan', '4nan']))
edge_blocked_tm = pd.crosstab(sessdf[edge_blocked_mask].port, sessdf[edge_blocked_mask].choice_t1, normalize = normalizing)
edge_blocked_tm[1] = empty_cell_val
edge_blocked_tm[4] = empty_cell_val
edge_blocked_tm.loc[1] = empty_cell_val
edge_blocked_tm.loc[4] = empty_cell_val
edge_blocked_tm = edge_blocked_tm.sort_index()[[1,2,3,4]]
sns.heatmap(edge_blocked_tm, cmap = parula, vmax = 0.15, vmin = 0, ax = ax, square = True, xticklabels = np.arange(1,5), yticklabels = np.arange(1,5))
ax.set_title('1,4 blocked')
# ax.patch.set_facecolor('white')

plt.tight_layout()

In [ ]:

plt.bar(np.array([0, 2, 3, 1])-0.4, [unblocked_tm.to_numpy()[3,2]+unblocked_tm.to_numpy()[2,3],
                       unblocked_tm.to_numpy()[0,2]+unblocked_tm.to_numpy()[2,0],
                       unblocked_tm.to_numpy()[0,3]+unblocked_tm.to_numpy()[3,0],
                       unblocked_tm.to_numpy()[1,2]+unblocked_tm.to_numpy()[2,1]], label = 'unblocked', width = 0.4)
plt.bar([0, 2, 3.4], [two_blocked_tm[2,3]+two_blocked_tm[3,2], two_blocked_tm[0, 2]+two_blocked_tm[2,0], two_blocked_tm[0,3]+two_blocked_tm[3, 0]], label = 'two blocked', width = 0.4)
plt.bar([1], edge_blocked_tm.to_numpy()[1, 2]+edge_blocked_tm.to_numpy()[2,1], label = 'edge blocked', width = 0.4)
plt.bar([3], centre_blocked_tm.to_numpy()[0, 3]+centre_blocked_tm.to_numpy()[3,0], label = 'centre blocked', width = 0.4)
plt.ylabel('Switch probability')
plt.xticks(np.array([0-0.2,1-.2,2-.2,3]), ['34, 43', '23, 32', '13, 31', '14, 41'])
plt.legend()
plt.tight_layout()